In [2]:
import numpy as np

In [3]:
a = np.ones([5,3])  # d,c
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
c = np.array([1,2,3])
a+c

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [7]:
np.maximum(0,a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
(a>1)*a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [35]:
b.shape

(5,)

In [19]:
b.dot(a)

array([15., 15., 15.])

In [29]:
c = np.array([[1,2,3,4,5]]*5)
c

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [30]:
c.dot(a)

array([[15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.]])

In [37]:
c

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [44]:
aa = np.array([[1, 2, 3,4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])
aa

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [49]:
(aa.T-b).T +1

array([[ 1,  2,  3,  4],
       [ 0,  1,  2,  3],
       [-1,  0,  1,  2],
       [-2, -1,  0,  1],
       [-3, -2, -1,  0]])

In [52]:
c[range(5),b]

IndexError: index 5 is out of bounds for axis 1 with size 5

In [110]:
aa

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [113]:
np.sum(aa,axis=0)

array([ 5, 10, 15, 20])

In [111]:
np.exp(aa)

array([[ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]])

In [120]:
d = np.array([0,1,2,1,3])
d

array([0, 1, 2, 1, 3])

In [121]:
np.exp(d)

array([ 1.        ,  2.71828183,  7.3890561 ,  2.71828183, 20.08553692])

In [122]:
np.log(2.718)

0.999896315728952

In [124]:
aa[range(5),d]

array([1, 2, 3, 2, 4])

In [81]:
a = np.array([-1,-23,5,6,])
a

array([ -1, -23,   5,   6])

In [83]:
(a>0) * a

array([0, 0, 5, 6])

In [84]:
aa

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [86]:
np.sum(aa)

50

In [101]:
a

array([ -1, -23,   5,   6])

In [104]:
np.exp(a)

array([3.67879441e-01, 1.02618796e-10, 1.48413159e+02, 4.03428793e+02])

In [88]:
(a>0).astype(int)

array([0, 0, 1, 1])

In [90]:
np.sum(aa, axis = 1)

array([10, 10, 10, 10, 10])

In [98]:
aa

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [99]:
aa[0][1],aa[1][1]

(2, 2)

In [100]:
np.argmax(aa,axis=1)

array([3, 3, 3, 3, 3], dtype=int64)

In [115]:
b1 = np.array([1,2,3,4,5])
b2 = np.array([2,2,2,2,2])
b1/b2

array([0.5, 1. , 1.5, 2. , 2.5])

In [116]:
np.log(b1/b2)

array([-0.69314718,  0.        ,  0.40546511,  0.69314718,  0.91629073])

In [125]:
aa

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [127]:
aa/b2.reshape(-1,1)

array([[0.5, 1. , 1.5, 2. ],
       [0.5, 1. , 1.5, 2. ],
       [0.5, 1. , 1.5, 2. ],
       [0.5, 1. , 1.5, 2. ],
       [0.5, 1. , 1.5, 2. ]])