In [4]:
for i in range(6,-1,-1):
    print(i)

6
5
4
3
2
1
0


In [3]:
for i in range(6, 0, -1):

SyntaxError: unexpected EOF while parsing (<ipython-input-3-a1e7deec6cc5>, line 1)

In [4]:
import numpy as np
x = np.asarray([[0, 3, 1, 2], [2, 1, 0, 3]]) # 2,4
w = np.linspace(0, 1, num=15).reshape(5,3) # 5,3
x,w

(array([[0, 3, 1, 2],
        [2, 1, 0, 3]]),
 array([[0.        , 0.07142857, 0.14285714],
        [0.21428571, 0.28571429, 0.35714286],
        [0.42857143, 0.5       , 0.57142857],
        [0.64285714, 0.71428571, 0.78571429],
        [0.85714286, 0.92857143, 1.        ]]))

In [7]:
w[x]

array([[[0.        , 0.07142857, 0.14285714],
        [0.64285714, 0.71428571, 0.78571429],
        [0.21428571, 0.28571429, 0.35714286],
        [0.42857143, 0.5       , 0.57142857]],

       [[0.42857143, 0.5       , 0.57142857],
        [0.21428571, 0.28571429, 0.35714286],
        [0.        , 0.07142857, 0.14285714],
        [0.64285714, 0.71428571, 0.78571429]]])